<a href="https://colab.research.google.com/github/Si-kaR/Ai_Space/blob/main/Assignment_2_Data_Munging_Stuff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Name : Robert Sika
# ID   : 89212025


# Assignment | Data Munging Stuff
# Due        | 29 Sep 23:59 | Week by 23:59

# Points     | 25
# File types | NO FILE
# Submitting | URL LINK UPLOAD
# Available  | 20 Sep at 11:00 - 29 Sep at 23:59

Submission Instructions

*    Use the Google Colab Platform for this assignment
*    Give the instructors permission to edit your Google Colab file at the file-sharing settings: kavutatenda@gmail.com, percy0.brown@gmail.com, kwekuandyamoah@gmail.com.
*    Submit the Link to the Colab File
*    Highlight the source code that corresponds to each question below using text/MarkDown on Google Colab
--      eg,
        How many bookings of arrestees were made in 2018?     
        source code:                       dataframe[columns].sort_values().

In [1]:
# import all necessary libraries and resources

import pandas as pd
import numpy as np
import json
import csv

In [3]:
# Mounting drive into Colab runtime

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
#  Reading from the 'arrest_data' csv file
read_arrest_data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ASSIGNMENTS/COLAB_Assignment_2/Arrest_Data_from_2010_to_Present.csv')


# Calling | Displaying content from the 'arrest_data' file
# Note: Will be displayed as DataFrame
read_arrest_data

<ipython-input-4-161ff1cf11d8>:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  read_arrest_data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ASSIGNMENTS/COLAB_Assignment_2/Arrest_Data_from_2010_to_Present.csv')

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
0,4248313,02/24/2015,1310.0,20.0,Olympic,2022.0,37.0,M,H,5.0,Burglary,F,459PC,BURGLARY,5TH,WILTON,"(34.0653, -118.314)"
1,191811472,05/03/2019,1700.0,18.0,Southeast,1802.0,23.0,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)"
2,4254777,02/26/2015,2010.0,19.0,Mission,1985.0,22.0,M,H,6.0,Larceny,M,459.5PC,SHOPLIFTING,8300 VAN NUYS BL,NaN,"(34.2216, -118.4488)"
3,5614161,04/29/2019,1040.0,8.0,West LA,842.0,41.0,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)"
4,5615197,04/30/2019,615.0,6.0,Hollywood,663.0,27.0,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227516,5238234,02/20/2018,2140.0,9.0,Van Nuys,905.0,17.0,M,H,24.0,Miscellaneous Other Violatio{,NaN,NaN,NaN,NaN,NaN,NaN
1227517,"""error"" : true",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227518,"""message"" : ""Internal error""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227519,"""status"" : 500",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227520,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* Amount or Quantity of Data in the file 'arrest_data' does not correspond with what has been displayed here. Why?
* Will Colab not display everything given how dense the data is?

In [5]:
read_arrest_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1227521 entries, 0 to 1227520
Data columns (total 17 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   Report ID                 1227521 non-null  object
 1   Arrest Date               1227517 non-null  object
 2   Time                      1227322 non-null  float64
 3   Area ID                   1227517 non-null  float64
 4   Area Name                 1227517 non-null  object
 5   Reporting District        1227517 non-null  float64
 6   Age                       1227517 non-null  float64
 7   Sex Code                  1227517 non-null  object
 8   Descent Code              1227517 non-null  object
 9   Charge Group Code         1139951 non-null  float64
 10  Charge Group Description  1139515 non-null  object
 11  Arrest Type Code          1227516 non-null  object
 12  Charge                    1227516 non-null  object
 13  Charge Description        1139987 non-null  object
 14  Address                   1227516 non-null  object
 15  Cross Street              707334 non-null   object
 16  Location                  1227516 non-null  object
dtypes: float64(5), object(12)
memory usage: 159.2+ MB

In [6]:
#Read head of dataset
read_arrest_data.head()

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
0,4248313,02/24/2015,1310.0,20.0,Olympic,2022.0,37.0,M,H,5.0,Burglary,F,459PC,BURGLARY,5TH,WILTON,"(34.0653, -118.314)"
1,191811472,05/03/2019,1700.0,18.0,Southeast,1802.0,23.0,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)"
2,4254777,02/26/2015,2010.0,19.0,Mission,1985.0,22.0,M,H,6.0,Larceny,M,459.5PC,SHOPLIFTING,8300 VAN NUYS BL,NaN,"(34.2216, -118.4488)"
3,5614161,04/29/2019,1040.0,8.0,West LA,842.0,41.0,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)"
4,5615197,04/30/2019,615.0,6.0,Hollywood,663.0,27.0,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)"

In [7]:
#Read tail of dataset
read_arrest_data.tail()

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
1227516,5238234,02/20/2018,2140.0,9.0,Van Nuys,905.0,17.0,M,H,24.0,Miscellaneous Other Violatio{,NaN,NaN,NaN,NaN,NaN,NaN
1227517,"""error"" : true",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227518,"""message"" : ""Internal error""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227519,"""status"" : 500",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227520,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

1. How many bookings of arrestees were made in 2018? [5]?

∇∇∇

> Indented block


- -   Source code :

In [10]:
# Checking number of bookings in 2018

#  Store arrest_day columns in variable. as well as corresponding rows.
column_dict = {index: value for index, value in enumerate(read_arrest_data['Arrest Date'])}

# Display 'Arrest Date ' column
column_dict

{0: '02/24/2015',
 1: '05/03/2019',
 2: '02/26/2015',
 3: '04/29/2019',
 4: '04/30/2019',
 5: '04/30/2019',
 6: '02/28/2015',
 7: '02/28/2015',
 8: '05/01/2019',
 9: '05/01/2019',
 10: '03/01/2015',
 11: '05/02/2019',
 12: '03/02/2015',
 13: '04/16/2019',
 14: '04/26/2019',
 15: '04/26/2019',
 16: '04/26/2019',
 17: '04/27/2019',
 18: '04/26/2019',
 19: '04/23/2019',
 20: '04/23/2019',
 21: '04/27/2019',
 22: '04/22/2019',
 23: '04/22/2019',
 24: '04/22/2019',
 25: '04/23/2019',
 26: '04/23/2019',
 27: '04/26/2019',
 28: '04/24/2019',
 29: '04/25/2019',
 30: '04/22/2019',
 31: '04/22/2019',
 32: '04/25/2019',
 33: '04/23/2019',
 34: '04/23/2019',
 35: '04/25/2019',
 36: '04/23/2019',
 37: '04/22/2019',
 38: '04/25/2019',
 39: '04/22/2019',
 40: '04/25/2019',
 41: '04/22/2019',
 42: '04/25/2019',
 43: '04/25/2019',
 44: '04/27/2019',
 45: '04/25/2019',
 46: '04/27/2019',
 47: '04/25/2019',
 48: '04/25/2019',
 49: '04/25/2019',
 50: '04/25/2019',
 51: '04/25/2019',
 52: '04/25/2019',
 53: '04/25/2019',
 54: '04/22/2019',
 55: '04/23/2019',
 56: '04/23/2019',
 57: '04/23/2019',
 58: '04/23/2019',
 59: '04/23/2019',
 60: '04/22/2019',
 61: '04/22/2019',
 62: '04/22/2019',
 63: '04/22/2019',
 64: '04/22/2019',
 65: '04/27/2019',
 66: '04/27/2019',
 67: '04/27/2019',
 68: '04/27/2019',
 69: '04/27/2019',
 70: '04/27/2019',
 71: '04/25/2019',
 72: '04/27/2019',
 73: '04/26/2019',
 74: '04/26/2019',
 75: '04/26/2019',
 76: '04/26/2019',
 77: '04/26/2019',
 78: '04/25/2019',
 79: '04/26/2019',
 80: '04/26/2019',
 81: '04/19/2019',
 82: '04/26/2019',
 83: '04/27/2019',
 84: '04/12/2019',
 85: '04/26/2019',
 86: '04/19/2019',
 87: '04/19/2019',
 88: '04/22/2019',
 89: '04/23/2019',
 90: '04/22/2019',
 91: '04/24/2019',
 92: '04/26/2019',
 93: '04/26/2019',
 94: '04/26/2019',
 95: '04/16/2019',
 96: '04/15/2019',
 97: '04/26/2019',
 98: '04/27/2019',
 99: '04/27/2019',
 100: '04/27/2019',
 101: '04/27/2019',
 102: '04/27/2019',
 103: '04/21/2019',
 104: '04/20/2019',
 105: '04/27/2019',
 106: '04/24/2019',
 107: '04/24/2019',
 108: '04/24/2019',
 109: '04/20/2019',
 110: '04/19/2019',
 111: '04/24/2019',
 112: '04/24/2019',
 113: '04/24/2019',
 114: '04/24/2019',
 115: '04/26/2019',
 116: '04/25/2019',
 117: '04/25/2019',
 118: '04/25/2019',
 119: '04/25/2019',
 120: '04/25/2019',
 121: '04/25/2019',
 122: '04/25/2019',
 123: '04/27/2019',
 124: '04/25/2019',
 125: '04/25/2019',
 126: '04/18/2019',
 127: '04/17/2019',
 128: '04/17/2019',
 129: '04/17/2019',
 130: '04/17/2019',
 131: '04/18/2019',
 132: '04/17/2019',
 133: '04/17/2019',
 134: '04/17/2019',
 135: '04/17/2019',
 136: '04/17/2019',
 137: '04/18/2019',
 138: '04/18/2019',
 139: '04/27/2019',
 140: '04/18/2019',
 141: '04/18/2019',
 142: '04/25/2019',
 143: '04/14/2019',
 144: '04/14/2019',
 145: '04/16/2019',
 146: '04/18/2019',
 147: '04/18/2019',
 148: '04/18/2019',
 149: '04/18/2019',
 150: '04/18/2019',
 151: '04/18/2019',
 152: '04/26/2019',
 153: '04/26/2019',
 154: '04/26/2019',
 155: '04/25/2019',
 156: '04/25/2019',
 157: '04/23/2019',
 158: '04/23/2019',
 159: '04/22/2019',
 160: '08/01/2016',
 161: '08/01/2016',
 162: '05/14/2017',
 163: '08/01/2017',
 164: '11/27/2017',
 165: '01/24/2018',
 166: '03/15/2018',
 167: '06/01/2018',
 168: '06/10/2018',
 169: '07/07/2018',
 170: '08/25/2018',
 171: '08/27/2018',
 172: '03/10/2019',
 173: '04/10/2017',
 174: '11/30/2017',
 175: '03/31/2019',
 176: '09/10/2018',
 177: '09/23/2018',
 178: '10/15/2018',
 179: '10/15/2018',
 180: '10/19/2018',
 181: '10/25/2018',
 182: '10/29/2018',
 183: '11/03/2018',
 184: '11/12/2018',
 185: '11/18/2018',
 186: '11/18/2018',
 187: '11/19/2018',
 188: '11/20/2018',
 189: '11/21/2018',
 190: '11/22/2018',
 191: '11/26/2018',
 192: '11/30/2018',
 193: '12/01/2018',
 194: '12/04/2018',
 195: '12/09/2018',
 196: '12/11/2018',
 197: '10/30/2018',
 198: '12/08/2018',
 199: '04/27/2019',
 200: '12/15/2018',
 201: '12/15/2018',
 202: '12/21/2018',
 203: '12/24/2018',
 204: '12/24/2018',
 205: '12/26/2018',
 206: '12/30/2018',
 207: '01/02/2019',
 208: '01/02/2019',
 209: '01/02/2019',
 210: '01/03/2019',
 211: '01/03/2019',
 212: '01/04/2019',
 213: '01/05/2019',
 214: '01/05/2019',
 215: '01/05/2019',
 216: '01/09/2019',
 217: '01/09/2019',
 218: '01/10/2019',
 219: '01/13/2019',
 220: '01/16/2019',
 221: '01/18/2019',
 222: '01/18/2019',
 223: '12/13/2018',
 224: '01/12/2019',
 225: '01/13/2019',
 226: '01/19/2019',
 227: '01/21/2019',
 228: '01/22/2019',
 229: '01/23/2019',
 230: '01/25/2019',
 231: '01/27/2019',
 232: '01/29/2019',
 233: '02/01/2019',
 234: '02/03/2019',
 235: '02/06/2019',
 236: '02/07/2019',
 237: '02/08/2019',
 238: '02/08/2019',
 239: '02/08/2019',
 240: '02/11/2019',
 241: '02/12/2019',
 242: '02/12/2019',
 243: '02/13/2019',
 244: '02/14/2019',
 245: '01/26/2019',
 246: '02/02/2019',
 247: '01/24/2019',
 248: '01/28/2019',
 249: '01/31/2019',
 250: '02/02/2019',
 251: '01/29/2019',
 252: '02/17/2019',
 253: '02/19/2019',
 254: '02/19/2019',
 255: '02/19/2019',
 256: '02/19/2019',
 257: '02/20/2019',
 258: '02/20/2019',
 259: '02/20/2019',
 260: '02/21/2019',
 261: '02/22/2019',
 262: '02/23/2019',
 263: '02/24/2019',
 264: '02/24/2019',
 265: '02/25/2019',
 266: '02/25/2019',
 267: '02/25/2019',
 268: '02/25/2019',
 269: '02/27/2019',
 270: '02/28/2019',
 271: '02/28/2019',
 272: '02/28/2019',
 273: '02/28/2019',
 274: '02/28/2019',
 275: '03/01/2019',
 276: '03/02/2019',
 277: '03/03/2019',
 278: '02/22/2019',
 279: '02/19/2019',
 280: '03/03/2019',
 281: '03/03/2019',
 282: '03/03/2019',
 283: '03/04/2019',
 284: '03/04/2019',
 285: '03/05/2019',
 286: '04/22/2019',
 287: '03/06/2019',
 288: '03/06/2019',
 289: '03/06/2019',
 290: '03/07/2019',
 291: '03/07/2019',
 292: '03/07/2019',
 293: '03/07/2019',
 294: '03/07/2019',
 295: '03/08/2019',
 296: '03/08/2019',
 297: '03/08/2019',
 298: '03/09/2019',
 299: '03/09/2019',
 300: '03/09/2019',
 301: '03/08/2019',
 302: '03/08/2019',
 303: '03/04/2019',
 304: '03/07/2019',
 305: '03/05/2019',
 306: '03/10/2019',
 307: '03/10/2019',
 308: '03/10/2019',
 309: '03/09/2019',
 310: '03/09/2019',
 311: '03/09/2019',
 312: '03/10/2019',
 313: '03/10/2019',
 314: '03/11/2019',
 315: '03/11/2019',
 316: '03/11/2019',
 317: '03/11/2019',
 318: '03/12/2019',
 319: '03/12/2019',
 320: '03/13/2019',
 321: '03/13/2019',
 322: '03/13/2019',
 323: '03/13/2019',
 324: '03/14/2019',
 325: '03/14/2019',
 326: '03/14/2019',
 327: '03/14/2019',
 328: '03/14/2019',
 329: '03/14/2019',
 330: '03/11/2019',
 331: '03/12/2019',
 332: '03/11/2019',
 333: '03/15/2019',
 334: '03/15/2019',
 335: '03/15/2019',
 336: '03/15/2019',
 337: '03/15/2019',
 338: '03/16/2019',
 339: '03/16/2019',
 340: '03/16/2019',
 341: '03/16/2019',
 342: '03/17/2019',
 343: '03/17/2019',
 344: '03/16/2019',
 345: '03/17/2019',
 346: '03/17/2019',
 347: '03/17/2019',
 348: '03/18/2019',
 349: '03/18/2019',
 350: '03/18/2019',
 351: '03/18/2019',
 352: '03/18/2019',
 353: '03/18/2019',
 354: '03/17/2019',
 355: '03/18/2019',
 356: '03/04/2015',
 357: '03/18/2019',
 358: '03/18/2019',
 359: '03/18/2019',
 360: '03/18/2019',
 361: '03/18/2019',
 362: '03/19/2019',
 363: '03/19/2019',
 364: '03/20/2019',
 365: '03/20/2019',
 366: '03/20/2019',
 367: '03/20/2019',
 368: '03/21/2019',
 369: '03/20/2019',
 370: '03/21/2019',
 371: '03/21/2019',
 372: '03/21/2019',
 373: '03/21/2019',
 374: '03/21/2019',
 375: '03/21/2019',
 376: '03/21/2019',
 377: '03/22/2019',
 378: '03/21/2019',
 379: '03/22/2019',
 380: '03/22/2019',
 381: '03/21/2019',
 382: '03/21/2019',
 383: '03/22/2019',
 384: '03/22/2019',
 385: '03/23/2019',
 386: '03/23/2019',
 387: '03/23/2019',
 388: '03/24/2019',
 389: '03/24/2019',
 390: '03/24/2019',
 391: '03/25/2019',
 392: '03/25/2019',
 393: '03/25/2019',
 394: '03/25/2019',
 395: '03/25/2019',
 396: '03/25/2019',
 397: '03/26/2019',
 398: '03/26/2019',
 399: '03/26/2019',
 400: '03/26/2019',
 401: '03/26/2019',
 402: '03/26/2019',
 403: '03/27/2019',
 404: '03/24/2019',
 405: '03/23/2019',
 406: '03/24/2019',
 407: '03/23/2019',
 408: '03/27/2019',
 409: '03/27/2019',
 410: '03/27/2019',
 411: '03/27/2019',
 412: '03/27/2019',
 413: '03/27/2019',
 414: '03/28/2019',
 415: '03/28/2019',
 416: '03/28/2019',
 417: '03/28/2019',
 418: '03/28/2019',
 419: '03/28/2019',
 420: '03/28/2019',
 421: '03/28/2019',
 422: '03/29/2019',
 423: '03/29/2019',
 424: '03/29/2019',
 425: '03/29/2019',
 426: '03/29/2019',
 427: '03/29/2019',
 428: '03/29/2019',
 429: '03/29/2019',
 430: '03/29/2019',
 431: '03/28/2019',
 432: '03/29/2019',
 433: '03/29/2019',
 434: '03/29/2019',
 435: '03/29/2019',
 436: '03/29/2019',
 437: '03/29/2019',
 438: '03/29/2019',
 439: '03/29/2019',
 440: '03/30/2019',
 441: '03/30/2019',
 442: '03/30/2019',
 443: '03/30/2019',
 444: '03/30/2019',
 445: '03/31/2019',
 446: '03/31/2019',
 447: '03/30/2019',
 448: '03/31/2019',
 449: '03/31/2019',
 450: '03/31/2019',
 451: '03/31/2019',
 452: '03/31/2019',
 453: '03/31/2019',
 454: '03/31/2019',
 455: '04/01/2019',
 456: '04/01/2019',
 457: '03/30/2019',
 458: '03/29/2019',
 459: '03/30/2019',
 460: '03/29/2019',
 461: '04/01/2019',
 462: '04/01/2019',
 463: '04/01/2019',
 464: '04/01/2019',
 465: '04/02/2019',
 466: '04/02/2019',
 467: '04/02/2019',
 468: '04/02/2019',
 469: '04/02/2019',
 470: '04/02/2019',
 471: '04/02/2019',
 472: '04/02/2019',
 473: '04/02/2019',
 474: '04/02/2019',
 475: '04/02/2019',
 476: '04/02/2019',
 477: '04/03/2019',
 478: '04/03/2019',
 479: '04/03/2019',
 480: '04/03/2019',
 481: '04/03/2019',
 482: '04/02/2019',
 483: '04/02/2019',
 484: '04/03/2019',
 485: '04/02/2019',
 486: '04/02/2019',
 487: '04/03/2019',
 488: '04/03/2019',
 489: '04/03/2019',
 490: '04/03/2019',
 491: '04/03/2019',
 492: '04/03/2019',
 493: '04/03/2019',
 494: '04/03/2019',
 495: '04/04/2019',
 496: '04/03/2019',
 497: '04/04/2019',
 498: '04/04/2019',
 499: '04/04/2019',
 500: '04/03/2019',
 501: '04/04/2019',
 502: '04/04/2019',
 503: '04/04/2019',
 504: '04/04/2019',
 505: '04/05/2019',
 506: '04/05/2019',
 507: '04/05/2019',
 508: '04/03/2019',
 509: '04/05/2019',
 510: '04/05/2019',
 511: '04/03/2019',
 512: '05/24/2019',
 513: '04/05/2019',
 514: '04/05/2019',
 515: '04/05/2019',
 516: '04/05/2019',
 517: '04/05/2019',
 518: '04/05/2019',
 519: '04/05/2019',
 520: '04/06/2019',
 521: '04/06/2019',
 522: '04/06/2019',
 523: '04/06/2019',
 524: '04/05/2019',
 525: '04/06/2019',
 526: '04/06/2019',
 527: '04/06/2019',
 528: '04/06/2019',
 529: '04/06/2019',
 530: '04/06/2019',
 531: '04/06/2019',
 532: '04/07/2019',
 533: '04/07/2019',
 534: '04/07/2019',
 535: '04/07/2019',
 536: '04/07/2019',
 537: '04/06/2019',
 538: '04/06/2019',
 539: '04/07/2019',
 540: '04/06/2019',
 541: '04/07/2019',
 542: '04/07/2019',
 543: '04/07/2019',
 544: '04/07/2019',
 545: '04/07/2019',
 546: '04/07/2019',
 547: '04/07/2019',
 548: '04/08/2019',
 549: '04/08/2019',
 550: '04/08/2019',
 551: '04/08/2019',
 552: '04/08/2019',
 553: '04/08/2019',
 554: '04/08/2019',
 555: '04/08/2019',
 556: '04/08/2019',
 557: '04/07/2019',
 558: '04/08/2019',
 559: '04/08/2019',
 560: '04/07/2019',
 561: '04/08/2019',
 562: '04/07/2019',
 563: '04/08/2019',
 564: '04/07/2019',
 565: '04/08/2019',
 566: '04/08/2019',
 567: '04/09/2019',
 568: '04/09/2019',
 569: '04/09/2019',
 570: '04/09/2019',
 571: '04/09/2019',
 572: '04/09/2019',
 573: '04/09/2019',
 574: '04/09/2019',
 575: '04/09/2019',
 576: '04/09/2019',
 577: '04/09/2019',
 578: '04/09/2019',
 579: '04/09/2019',
 580: '04/10/2019',
 581: '04/10/2019',
 582: '04/10/2019',
 583: '04/10/2019',
 584: '04/10/2019',
 585: '04/10/2019',
 586: '04/10/2019',
 587: '04/08/2019',
 588: '04/09/2019',
 589: '04/09/2019',
 590: '04/10/2019',
 591: '04/10/2019',
 592: '04/10/2019',
 593: '04/10/2019',
 594: '04/10/2019',
 595: '04/10/2019',
 596: '04/10/2019',
 597: '04/10/2019',
 598: '04/10/2019',
 599: '04/10/2019',
 600: '04/10/2019',
 601: '04/11/2019',
 602: '04/11/2019',
 603: '04/11/2019',
 604: '04/11/2019',
 605: '04/10/2019',
 606: '04/10/2019',
 607: '04/11/2019',
 608: '04/10/2019',
 609: '04/10/2019',
 610: '04/10/2019',
 611: '04/10/2019',
 612: '04/11/2019',
 613: '04/11/2019',
 614: '04/11/2019',
 615: '04/11/2019',
 616: '04/11/2019',
 617: '04/11/2019',
 618: '04/11/2019',
 619: '04/11/2019',
 620: '04/11/2019',
 621: '04/12/2019',
 622: '04/11/2019',
 623: '04/11/2019',
 624: '04/12/2019',
 625: '04/12/2019',
 626: '04/12/2019',
 627: '04/12/2019',
 628: '04/12/2019',
 629: '04/12/2019',
 630: '04/12/2019',
 631: '04/12/2019',
 632: '04/12/2019',
 633: '04/11/2019',
 634: '04/12/2019',
 635: '04/12/2019',
 636: '04/12/2019',
 637: '04/12/2019',
 638: '04/11/2019',
 639: '04/12/2019',
 640: '04/12/2019',
 641: '04/12/2019',
 642: '04/12/2019',
 643: '04/12/2019',
 644: '04/12/2019',
 645: '04/12/2019',
 646: '04/12/2019',
 647: '04/12/2019',
 648: '04/12/2019',
 649: '04/12/2019',
 650: '04/12/2019',
 651: '04/12/2019',
 652: '04/13/2019',
 653: '04/12/2019',
 654: '04/13/2019',
 655: '04/12/2019',
 656: '04/12/2019',
 657: '04/13/2019',
 658: '04/13/2019',
 659: '04/13/2019',
 660: '04/12/2019',
 661: '04/12/2019',
 662: '04/13/2019',
 663: '04/12/2019',
 664: '04/13/2019',
 665: '04/13/2019',
 666: '04/13/2019',
 667: '04/13/2019',
 668: '04/13/2019',
 669: '04/13/2019',
 670: '04/13/2019',
 671: '04/13/2019',
 672: '04/13/2019',
 673: '04/13/2019',
 674: '04/13/2019',
 675: '04/13/2019',
 676: '04/14/2019',
 677: '04/14/2019',
 678: '04/14/2019',
 679: '04/14/2019',
 680: '04/14/2019',
 681: '04/14/2019',
 682: '04/14/2019',
 683: '04/14/2019',
 684: '04/14/2019',
 685: '04/14/2019',
 686: '04/13/2019',
 687: '04/13/2019',
 688: '04/14/2019',
 689: '04/13/2019',
 690: '04/14/2019',
 691: '04/14/2019',
 692: '04/14/2019',
 693: '04/14/2019',
 694: '04/14/2019',
 695: '04/14/2019',
 696: '04/14/2019',
 697: '04/14/2019',
 698: '04/14/2019',
 699: '04/14/2019',
 700: '04/15/2019',
 701: '04/15/2019',
 702: '04/14/2019',
 703: '04/15/2019',
 704: '04/15/2019',
 705: '04/15/2019',
 706: '04/15/2019',
 707: '04/15/2019',
 708: '04/15/2019',
 709: '04/14/2019',
 710: '04/14/2019',
 711: '04/15/2019',
 712: '04/14/2019',
 713: '04/15/2019',
 714: '04/15/2019',
 715: '04/14/2019',
 716: '04/15/2019',
 717: '04/15/2019',
 718: '04/15/2019',
 719: '04/15/2019',
 720: '04/15/2019',
 721: '04/15/2019',
 722: '04/15/2019',
 723: '04/15/2019',
 724: '04/15/2019',
 725: '04/15/2019',
 726: '04/16/2019',
 727: '04/16/2019',
 728: '04/16/2019',
 729: '04/16/2019',
 730: '04/16/2019',
 731: '04/16/2019',
 732: '04/16/2019',
 733: '04/16/2019',
 734: '04/15/2019',
 735: '04/16/2019',
 736: '04/16/2019',
 737: '04/16/2019',
 738: '04/15/2019',
 739: '04/15/2019',
 740: '04/15/2019',
 741: '04/16/2019',
 742: '04/16/2019',
 743: '04/16/2019',
 744: '04/16/2019',
 745: '04/16/2019',
 746: '04/16/2019',
 747: '04/16/2019',
 748: '04/16/2019',
 749: '04/16/2019',
 750: '04/17/2019',
 751: '04/17/2019',
 752: '04/16/2019',
 753: '04/17/2019',
 754: '04/17/2019',
 755: '04/17/2019',
 756: '04/17/2019',
 757: '04/17/2019',
 758: '04/17/2019',
 759: '04/16/2019',
 760: '04/16/2019',
 761: '04/16/2019',
 762: '04/16/2019',
 763: '04/16/2019',
 764: '04/17/2019',
 765: '04/17/2019',
 766: '04/17/2019',
 767: '04/17/2019',
 768: '04/17/2019',
 769: '04/17/2019',
 770: '04/17/2019',
 771: '04/17/2019',
 772: '04/17/2019',
 773: '04/17/2019',
 774: '04/17/2019',
 775: '04/17/2019',
 776: '04/17/2019',
 777: '04/17/2019',
 778: '04/17/2019',
 779: '04/18/2019',
 780: '04/18/2019',
 781: '04/18/2019',
 782: '04/17/2019',
 783: '04/17/2019',
 784: '04/18/2019',
 785: '04/17/2019',
 786: '04/17/2019',
 787: '04/17/2019',
 788: '04/18/2019',
 789: '04/18/2019',
 790: '04/18/2019',
 791: '04/18/2019',
 792: '04/18/2019',
 793: '04/18/2019',
 794: '04/18/2019',
 795: '04/18/2019',
 796: '04/18/2019',
 797: '04/18/2019',
 798: '04/18/2019',
 799: '04/18/2019',
 800: '04/18/2019',
 801: '04/18/2019',
 802: '04/18/2019',
 803: '04/18/2019',
 804: '04/18/2019',
 805: '04/18/2019',
 806: '04/18/2019',
 807: '04/18/2019',
 808: '04/18/2019',
 809: '04/18/2019',
 810: '04/18/2019',
 811: '04/18/2019',
 812: '04/18/2019',
 813: '04/18/2019',
 814: '04/18/2019',
 815: '04/19/2019',
 816: '04/18/2019',
 817: '04/18/2019',
 818: '04/18/2019',
 819: '04/19/2019',
 820: '04/18/2019',
 821: '04/18/2019',
 822: '04/19/2019',
 823: '04/19/2019',
 824: '04/19/2019',
 825: '04/19/2019',
 826: '04/19/2019',
 827: '04/19/2019',
 828: '04/19/2019',
 829: '04/19/2019',
 830: '04/19/2019',
 831: '04/19/2019',
 832: '04/19/2019',
 833: '04/18/2019',
 834: '04/18/2019',
 835: '04/19/2019',
 836: '04/19/2019',
 837: '04/19/2019',
 838: '04/19/2019',
 839: '04/19/2019',
 840: '04/19/2019',
 841: '04/19/2019',
 842: '04/19/2019',
 843: '04/19/2019',
 844: '04/19/2019',
 845: '04/19/2019',
 846: '04/19/2019',
 847: '04/19/2019',
 848: '04/19/2019',
 849: '04/19/2019',
 850: '04/19/2019',
 851: '04/19/2019',
 852: '04/19/2019',
 853: '04/19/2019',
 854: '04/19/2019',
 855: '04/19/2019',
 856: '04/19/2019',
 857: '04/19/2019',
 858: '04/19/2019',
 859: '08/14/2019',
 860: '04/19/2019',
 861: '04/19/2019',
 862: '04/19/2019',
 863: '04/20/2019',
 864: '04/20/2019',
 865: '04/20/2019',
 866: '04/20/2019',
 867: '04/20/2019',
 868: '04/20/2019',
 869: '04/20/2019',
 870: '04/20/2019',
 871: '04/20/2019',
 872: '04/20/2019',
 873: '04/20/2019',
 874: '04/20/2019',
 875: '04/20/2019',
 876: '04/20/2019',
 877: '04/20/2019',
 878: '04/20/2019',
 879: '04/20/2019',
 880: '04/20/2019',
 881: '04/20/2019',
 882: '04/20/2019',
 883: '04/20/2019',
 884: '04/20/2019',
 885: '04/20/2019',
 886: '04/20/2019',
 887: '04/20/2019',
 888: '04/20/2019',
 889: '04/20/2019',
 890: '04/20/2019',
 891: '04/20/2019',
 892: '04/21/2019',
 893: '04/21/2019',
 894: '04/21/2019',
 895: '04/21/2019',
 896: '04/21/2019',
 897: '04/21/2019',
 898: '04/21/2019',
 899: '04/21/2019',
 900: '04/21/2019',
 901: '04/21/2019',
 902: '04/21/2019',
 903: '04/21/2019',
 904: '04/22/2019',
 905: '04/21/2019',
 906: '04/21/2019',
 907: '04/21/2019',
 908: '04/21/2019',
 909: '04/21/2019',
 910: '04/21/2019',
 911: '04/22/2019',
 912: '04/22/2019',
 913: '04/22/2019',
 914: '04/22/2019',
 915: '04/22/2019',
 916: '04/22/2019',
 917: '04/22/2019',
 918: '04/22/2019',
 919: '04/22/2019',
 920: '04/22/2019',
 921: '04/22/2019',
 922: '04/22/2019',
 923: '04/22/2019',
 924: '04/22/2019',
 925: '04/22/2019',
 926: '04/22/2019',
 927: '04/22/2019',
 928: '04/22/2019',
 929: '04/22/2019',
 930: '04/22/2019',
 931: '04/22/2019',
 932: '04/22/2019',
 933: '04/22/2019',
 934: '04/22/2019',
 935: '04/23/2019',
 936: '04/23/2019',
 937: '04/22/2019',
 938: '04/23/2019',
 939: '04/23/2019',
 940: '04/23/2019',
 941: '04/23/2019',
 942: '04/23/2019',
 943: '04/23/2019',
 944: '04/23/2019',
 945: '04/23/2019',
 946: '04/23/2019',
 947: '04/23/2019',
 948: '04/23/2019',
 949: '04/23/2019',
 950: '04/23/2019',
 951: '04/23/2019',
 952: '04/22/2019',
 953: '04/23/2019',
 954: '04/23/2019',
 955: '04/23/2019',
 956: '04/23/2019',
 957: '04/23/2019',
 958: '04/23/2019',
 959: '04/23/2019',
 960: '04/23/2019',
 961: '04/23/2019',
 962: '04/23/2019',
 963: '04/23/2019',
 964: '04/23/2019',
 965: '04/23/2019',
 966: '04/24/2019',
 967: '04/24/2019',
 968: '04/23/2019',
 969: '04/23/2019',
 970: '04/23/2019',
 971: '04/23/2019',
 972: '04/24/2019',
 973: '04/24/2019',
 974: '04/24/2019',
 975: '04/24/2019',
 976: '04/24/2019',
 977: '04/24/2019',
 978: '04/24/2019',
 979: '04/24/2019',
 980: '04/24/2019',
 981: '04/24/2019',
 982: '04/24/2019',
 983: '04/24/2019',
 984: '04/24/2019',
 985: '04/24/2019',
 986: '04/24/2019',
 987: '04/24/2019',
 988: '04/24/2019',
 989: '04/24/2019',
 990: '04/24/2019',
 991: '04/24/2019',
 992: '04/24/2019',
 993: '04/24/2019',
 994: '04/24/2019',
 995: '04/24/2019',
 996: '04/24/2019',
 997: '04/24/2019',
 998: '04/24/2019',
 999: '04/24/2019',
 ...}

In [17]:
# Iterate through the column, split the date into three elements at the slashes (/).

# Afterwards, focusing on the years only, we can obtain the years 2018.
# Finally, we can find the length of the 2018s.

# Check for NULL or Nan Values
# If np returnes NOT NULL or NOT Nan, we negate and let display the values that are not Nan


for key, value in column_dict.items():
  if not np.isnan(value):
    value_list = str.split(value, '/')

TypeError: ignored

2. How many bookings of arrestees were made in each area and which area has the most arrests in 2018?[5]

∇∇∇
- -   Source code :

In [ ]:
# Checking number of arrests in each area


# Checking which area has the most arrests in 2018

3. There are differences between the average age of an arrestee for the various charge groups. Find the average age of arrestees per each charge group.

    

*   Only consider data for 2018
*   Do not consider "Pre-Delinquency" and "Non-Criminal Detention" as these charge groups are reserved for minors
*   Exclude any arrests where the charge group description is not known        [5]

∇∇∇
- -   Source code :

In [ ]:
# Finding average age of arrestees per each charge group

4. What is the 95% quantile of the age of the arrestee in 2018? Only consider the following charge groups for your analysis:

*    Vehicle Theft
*    Robbery
*    Burglary
*    Receive Stolen Property   

∇∇∇

- - Source Code :

In [ ]:
# Finding the 95% quantile of the age of the arrestee in 2018.

5. Crime arrest incidents have been dropping over the years. Using a linear regression for the data from 2010 and 2018 (inclusive), predict the number of crime arrests in 2019. Round to the nearest integer. Note, that the data set includes arrests for misdemeanor, felonies, etc.

∇∇∇

- - Source Code :

In [ ]:
# Focusing on data from 2010 to 2018 (inclusive)
# Predicting the number of crime arrests in 2019.